#!/bin/sh

dir=`dirname "$0"`
logdir="$dir/../www/logs"
cd $dir

/usr/bin/nice -19 /usr/bin/php -f cron.php headers $1 > $logdir/headers-$1.html
/usr/bin/nice -19 /usr/bin/php -f cron.php posts > $logdir/posts.html
/usr/bin/nice -19 /usr/bin/php -f cron.php nzb > $logdir/nzb.html